name: goreleaser

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run without publishing
        type: boolean
        default: true
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.17
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean ${{ inputs.dry-run && '--skip=publish' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
